site_name: Wording
site_author: Samir Romdhani
site_url: "https://romdhanisam.github.io/rev/"
repo_url: "https://github.com/romdhanisam/rev/"
repo_name: "romdhanisam/rev"
docs_dir: docs
site_dir: public

nav:
  - About: index.md
  - OOP: oop.md
  - Java: java.md
  - Design - Pattern: patterns.md
  - Spring: spring.md
  - BDD: bdd.md
  - Angular: angular.md
  - Note - Arch: arch.md
  - DevOps: devops.md
  - Microprofile-: Microprofile-SOA-microservice-JavaEE.md
  - Kafka-: kafka-.md
#  - Articles: articles.md

theme:
  name: material
  locale: fr
  favicon: https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/materialformkdocs.svg
  custom_dir: docs/overrides
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.sections
    - navigation.expand
#    - navigation.prune
    - search.suggest      # Enable suggestions
    - search.highlight    # Highlight search terms

plugins:
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - include-markdown
  - search
  - i18n:
      docs_structure: suffix
      default_language: fr
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          site_name: "Wording"
          nav_translations:
            Articles: Articles

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - footnotes
  - neoteroi.timeline
  - neoteroi.cards
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - assets/css/extra.css
  - assets/css/neoteroi-cards.css
  - assets/css/neoteroi-mkdocs.css
extra_javascript:
  - assets/js/extra.js
#extra:
#  status:
#    draft: "⚠️ Draft"
#    done: "✅"
