site_name: Wording
site_author: Samir Romdhani
site_url: "https://romdhanisam.github.io/rev/"
repo_url: "https://github.com/romdhanisam/rev/"
repo_name: "romdhanisam/rev"
docs_dir: docs
site_dir: public

nav:
  - About: index.md
  - OOP: oop.md
  - Java: java.md
  - Design - Pattern:
      - patterns.md
      - patterns_annexe.md
  - Spring: spring.md
  - BDD: bdd.md
  - Java-Spring-BDD: java-spring-words.md
  - Angular: angular.md
  - Architecture: arch.md
  - DevOps: devops.md
  - Kafka-: kafka-.md
  - Notes-: note.md
#  - Microprofile-: Microprofile-SOA-microservice-JavaEE.md
#  - Réseaux-: reseau.md
#  - Articles: articles.md
#  - Embedding a PDF file: files/speach10m.pdf

theme:
  name: material
  locale: fr
  favicon: https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/materialformkdocs.svg
  custom_dir: docs/overrides
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.footer
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.sections
    - navigation.expand
#    - navigation.prune
    - search.suggest      # Enable suggestions
    - search.highlight    # Highlight search terms
  icon:
    annotation: material/arrow-right-circle

plugins:
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - include-markdown
  - search
  - i18n:
      docs_structure: suffix
      default_language: fr
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          site_name: "Wording"
          nav_translations:
            Articles: Articles

markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - footnotes
  - neoteroi.timeline
  - neoteroi.cards
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - pymdownx.pathconverter:
#      base_path: 'https://romdhanisam.github.io/rev' # default: ''
#      relative_path: '' # default ''
#      absolute: true # default: false
#      tags: 'a script img link object embed'

extra_css:
  - assets/css/extra.css
  - assets/css/neoteroi-cards.css
  - assets/css/neoteroi-mkdocs.css
extra_javascript:
  - assets/js/extra.js
#extra:
#  status:
#    draft: "⚠️ Draft"
#    done: "✅"
